### PR TITLE
#83 - Refactor to use Dio instead of HTTP

### PR DESCRIPTION
**Pull request by miguelpruivo**
## This PR will
- Refactor to use DIO instead of `http` by providing an utils method that use the same DIO instance to perform the requests;
- Update the `flutter_map`, `firebase_messaging` and `flutter_svg` to the latest versions in order to fix the build due to a Flutter SDK change.

### CODE REVIEW

**Comment by guivazcabral** [comment]
Seems like you missed the commit with the Dio changes.

Also, what flutter SDK version are you using? I'm on Flutter's `stable` channel, just updated it and my build works fine. This is what we're working with: 

```
➜  fogosmobile git:(dev) ✗ flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • ssh://git@github.com/flutter/flutter.git
Framework • revision 7a4c33425d (8 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by miguelpruivo** [comment]
@guivazcabral my bad, I had it stashed. 😅 It is now committed. I'm on dev @ 1.7.3.

**Comment by guivazcabral** [comment]
No problem.

Yeah we'll be using the `stable` channel, for stability sake. So it means that your version upgrade will actually break stuff (that's also why Codemagic build failed).

I suggest you revert those changes on this PR. I would also suggest opening a separate PR for those package version's bump, but isn't it already done on @Vanethos PR #79 ?

**Comment by miguelpruivo** [comment]
@guivazcabral no problem, it should run fine anyway with the current dev pubspec.yaml version. Just committed a rollback for it.

**Comment by guivazcabral** [comment]
> it should run fine anyway with the current dev pubspec.yaml

no it wouldn't work with the pubspec.yml you had because, for example, the `flutter_map` version you had requires `flutter 1.5.9` when the `stable` is 1.5.4

**Comment by miguelpruivo** [comment]
> > it should run fine anyway with the current dev pubspec.yaml
> 
> no it wouldn't work with the pubspec.yml you had because, for example, the `flutter_map` version you had requires `flutter 1.5.9` when the `stable` is 1.5.4

No. I was talking about the other changes (refactor to use DIO), not the `pubspec.yaml` versions.

**Comment by miguelpruivo** [comment]
> > it should run fine anyway with the current dev pubspec.yaml
> 
> no it wouldn't work with the pubspec.yml you had because, for example, the `flutter_map` version you had requires `flutter 1.5.9` when the `stable` is 1.5.4

@guivazcabral no. I was talking about the other changes (refactor to use DIO), not the pubspec.yaml versions.

**Comment by miguelpruivo** [comment]
> > it should run fine anyway with the current dev pubspec.yaml
> 
> no it wouldn't work with the pubspec.yml you had because, for example, the `flutter_map` version you had requires `flutter 1.5.9` when the `stable` is 1.5.4

@guivazcabral no. I was referring to the other changes (refactor to use DIO), not the pubspec.yaml versions.

**Comment by Vanethos** [comment]
How are we on this PR?

**Comment by Vanethos** [comment]
Since this is needed for testing, I will approve this.

I used it and everything seems ok

**Pull request merged**
