### PR TITLE
FIx for #78

### LINKED ISSUE #78: Error in flutter_maps plugin when compiling

### PR DESCRIPTION
**Pull request by Vanethos**
Temporary solution until flutter_maps is updated

Closes #78

### CODE REVIEW

**Comment by Vanethos** [comment]
This has dependencies from git, so I assume codecommit can't handle it?

**Comment by miguelpruivo** [comment]
@Vanethos I've updated your `pubspec.yaml` file as well so it points to the right dependency. You've added it to the lock file which shouldn't be edited directly. Anyway, it looks like Codemagic is still failing somehow.

My first guess is that it may be related to the fact of dependency's cache from the git and pub.dev being stored in different folders.

**Comment by miguelpruivo** [comment]
@Vanethos I've updated your pubspec.yaml file so it points to the right dependency. You've added it to the lock file which shouldn't be edited directly. Anyway, it looks like Codemagic is still failing somehow.

My first guess is that it may be related to the fact of dependency's cache from the git and pub.dev being stored in different folders.

**Comment by Vanethos** [comment]
Funny thing is; I didn't edit it directly 🤔 

At least with codecommit we had to create a specific user to access the dependency in the repo, don't know if this is the same case

**Comment by miguelpruivo** [comment]
@guivazcabral even though the build is failing in codemagic (I don't have access to the logs, so it doesn't help much), it should be fine to merge right now. I've pushed an update to this @Vanethos  branch with both `flutter_map` and `flutter_svg` versions updated to valid versions that shouldn't break the build.

**Comment by guivazcabral** [comment]
From what I recall, this PR aimed to fix incompatibility between flutter_map and the Beta version of Flutter. Since we're not using the Beta version, I didn't merge it because it wasn't needed. The build on codemagic is failing because the versions of the packages `flutter_map` and `flutter_svg` require a more recent Flutter version that we are using. I won't merge this until we need it

**Comment by Vanethos** [comment]
This issue was closed since the solution might be different for the present flutter version and should be re-evaluated

**Comment by Vanethos** [comment]
@guivazcabral since I don't have access to it, what is the problem with this commit?

**Pull request merged**
