### PR TITLE
#24 Add translations to the app

### LINKED ISSUE #24: Add Intl translations to the app
Using the [intl_translation](https://pub.dev/packages/intl_translation) add translations to the app

### PR DESCRIPTION
**Pull request by Vanethos**
Add intl related packages
Add translations for all the strings in the app
Add documentation for how to create new translations

closes #24

### CODE REVIEW

**Comment by guivazcabral** [comment]
@Vanethos this looks good. Is the language depending on the system's language?
Also, there's a conflict that must be solved.

**Comment by Vanethos** [comment]
@guivazcabral yep! you can truy changing the system language and see it in action

Resolved the conflicts

**Comment by guivazcabral** [comment]
How hard is it to add an option to change language based on a preference setting?

**Comment by Vanethos** [comment]
Why do we want that in the app?

If the user has the phone in english, he must want to see the content in
english no?

And it may not be hard, but I have to investigate first, I'd suggest to
close this PR and make a new issue.

**Comment by Vanethos** [comment]
@guivazcabral could you try with the latest commit? I don't have any error on my side

**Comment by Vanethos** [comment]
As soon as I can I'll resolve the conflicts

**Pull request merged**
