### PR TITLE
#16 Add Copyright to mapbox

### PR DESCRIPTION
**Pull request by Lima21**

### CODE REVIEW

**Comment by guivazcabral** [comment]
closes: #16

**Comment by Vanethos** [comment]
The Implementation is great, however, you should take into consideration:
- Currently in an iPhone XR this occupies most of the screen, what would happen in smaller screen? Did you try like stated in the Issue where you have each "link" in a new line?
- There isn't any visual feedback that the text is clickable, can the text be underlined?
Simulator Screen Shot - iPhone XR - 2019-05-08 at 19 21 32

Also, @guivazcabral you agree with the text having a box in the background?

**Comment by guivazcabral** [comment]
I agree that it should be multi line. I'm ok with the background color, but I think it can be tweaked to make it more seamless (like a darker grey on the background or a lighter font color). My other thoughts:

- font looks too big.
- there's an extra &copy; before "Improve this map" that shouldn't be there.

**Comment by Lima21** [comment]
I ran this in a small screen and the text overflow the screen, so is to put one per line or try create a responsive layout?

**Comment by Vanethos** [comment]
@Lima21 You should Wrap that widget with a SafeArea (https://docs.flutter.io/flutter/widgets/SafeArea-class.html) so that it doesn't appear above the iphone X home bar or another phone's strange UI

Make it multiline and response if possible.

Also:

- You should add padding between the background and the text
- Add underline to the text to show that it's clickable

**Comment by guivazcabral** [comment]
Make it multi line and add the underline like @Vanethos suggested before

Quick tip: on the Simulator, hitting CMD+S saves a screenshot to your desktop folder without the iPhone's body. ;)

**Comment by Lima21** [comment]
I already did all the suggestions, but I'm not sure about the background color of the box

Simulator Screen Shot - iPhone Xʀ - 2019-05-09 at 13 16 17

**Comment by Vanethos** [comment]
This is excellent!

It's all good on my side, can we approve it @guivazcabral ?

**Pull request merged**
