### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by 0rp3u**
Small UI fixes, issue #42

### CODE REVIEW

**Comment by guivazcabral** [comment]
This looks great, although the dividers in the app Drawer were fine: they should be used to divide groups of actions (e.g. [Avisos, Informações] (Divider) [Notificações] (Divider) [Parcerias]), because they lead to different pages with different subjects throughout the app.

**Comment by 0rp3u** [comment]
Using dividers to group actions makes a lot of sense, but I don't see the relation between the ones grouped before.

**Comment by guivazcabral** [comment]
[Avisos, Informações] are a group of pages containing content related to the app's purpose
[Notificações] is a page where the user can change some preferences (actually "Notifications" is not a really suitable name for that menu item, but that's a discussion for other time)
[Parcerias] is a page more about how the app was built and with info about the project's institutional supporters (and not at all related to wildfires).

See what I mean?

**Comment by 0rp3u** [comment]
Ok I understand the grouping of avisos and informações, but not notificações and parcerias, although parcerias and the, in development, sobre page make sense to be paired. What do you think?

**Comment by guivazcabral** [comment]
I was not saying that Notificações e Parcerias are in the same group. As I said in my first comment

> [Avisos, Informações] (Divider) [Notificações] (Divider) [Parcerias]

where each bracket `[ ]` is a group. 

I agree with the about page being in the Parcerias group

**Comment by 0rp3u** [comment]
Screenshot_2019-05-21-12-34-42
hope this is more in line with what you pretend, Sobre will be grouped with Parcerias on the About issue.

**Comment by Vanethos** [comment]
@0rp3u It seems that there are some conflicts, could you try to fix that?

Thanks!!

**Comment by guivazcabral** [comment]
I think you re-added the divider when solving your conflicts. Fixed it on my end. Approving and merging now

**Pull request merged**
